### ISSUE TITLE
ignore <pre>

### ISSUE THREAD

**Issue by lepture** [Denkiame/Tategaki#5]
Don't parse text in `<pre>` element:

![image](https://user-images.githubusercontent.com/290496/138230578-545d1e6f-2142-451b-8253-ad62d7f62c6f.png)

**Comment by E8D08F** [comment]
Thanks for your report.

**Comment by lepture** [comment]
是不是也要 ignore 掉 `<code>`?

**Comment by E8D08F** [comment]
的確。已經修正。
